apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::235028800035:role/eksctl-eksctl-demo-nodegroup-ng-3-NodeInstanceRole-HFWSJ4YO5QQ7
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::235028800035:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-13T03:24:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1687"
  uid: 9a539e17-9f88-4854-8d7d-a25ade5ba454
